### PR TITLE
Added particles for when the ore is touched

### PR DESCRIPTION
**Pull request by MrIbby**
Screenshot

**Requires Java 8**

Features:
* Ender ore behaves like redstone ore, but with purple dust
* `BlockBaseEnderOre` reduces duplicate code

If necessary, I can modify the code to avoid the Java 8 requirement and/or to change the color of the particles.

### CODE REVIEW

**Comment by ProxyNeko** [comment]
Thank you very much for helping with this! I had not thought of a way to do the three ores with there own endermanSpawn config in the one class so this is great I'll add it in as soon as I get to work :D

**Comment by Mohron** [comment]
Now that this PR brings the ore to mostly one class file anyways, have you thought about using variants instead of separate blocks for the different ore textures?

**Comment by ProxyNeko** [comment]
The only mods that I can think of that even do that are Draconic Evolution and its requirement Brandons Core so while I would love to be able to do that it's a matter of how without just ripping his code off. (In short it is on the todo list but is not something I will be able to do before the next planned out release)

**Comment by Mohron** [comment]
Vanilla uses variants... all the different Stone Bricks for instance are just variants. I'm not talking about the old DE ore that dynamically changes texture by dim, just a single class that drives all three ores.

**Comment by MrIbby** [comment]
Variants are actually a good idea. I'll see if I can implement that.

**Comment by Mohron** [comment]
@ProxyNeko looks like @MrIbby is gonna take this little mod to the next level!

**Comment by ProxyNeko** [comment]
Tell me about it haha I'll try get that thing I wanted working and if its done by the end of tonight I may push out an update :)

**Pull request merged**
